#!/bin/sh

# SPDX-License-Identifier: zlib-acknowledgement
_dark_red_fg=$'\e[01;31m'
_colour_reset=$'\e[0m'

xmsg() {
  printf "${_dark_red_fg}\
${1}\n\
${_colour_reset}" >&2
  exit 1
}

test ${EUID} -eq 0 && \
  xmsg "CANNOT BE ROOT TO IMPORT GPG/SSH KEYS FOR USER!"

test ! -f 'private-key.asc' && \
  xmsg "REQUIRE GPG PRIVATE-KEY.ASC TO BE IN ${PWD}"

test ! -f '.ssh/id_rsa' -o ! -f '.ssh/id_rsa.pub' && \
  xmsg "REQUIRE .SSH FOLDER TO BE POPULATED IN ${PWD}"

command -v git >/dev/null 2>&1 && \
  xmsg "REQUIRE GIT TO BE INSTALLED"

command -v gpg >/dev/null 2>&1 && \
  xmsg "REQUIRE GPG TO BE INSTALLED"

git clone \
  'https://github.com/aruhier/gnome-terminal-colors-solarized.git'
cd 'gnome-terminal-colors-solarized'
./install.sh --install-dircolors
cd -
rm -rf 'gnome-terminal-colors-solarized'

ln -sf "~" .bashrc, .inputrc, .gdbinit

# PUT IN SCRIPTS REPO
# IMPORTANT(Ryan): Contained in /proc/sys/kernel. Sysctl will modify kernel parameters at
# run time
sudo sh -c 'echo kernel.perf_event_paranoid=1 >> /etc/sysctl.d/local.conf'
sudo sh -c 'echo kernel.yama.ptrace_scope=0 >> /etc/sysctl.d/local.conf'

sudo add-apt-repository ppa:ryan-mcclue/ppa-test -y
sudo apt install ubuntu-unity-desktop

mkdir -p "~/prog/personal" \
  "~/prog/apps" \
  "~/prog/sources" \
  "~/prog/toolchains"

git clone scripts

gpg --import private-key.asc
mkdir ~/.ssh
cp -r .ssh/. ~/.ssh 
chmod 600 ~/.ssh/id_rsa 
ssh-add


printf "${green}CONFIGURING VIM\n${reset}"
wget https://raw.githubusercontent.com/ryan-mcclue/cas/main/.vimrc -O ~/.gvimrc
wget https://raw.githubusercontent.com/ryan-mcclue/cas/main/.vimrc -O ~/.vimrc
mkdir -p ~/.vim/colors
wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim \
  -O ~/.vim/colors/solarized.vim


printf "${green}CONFIGURING GIT\n${reset}"
git config --global user.name "Ryan McClue"
git config --global user.email "re.mcclue@protonmail.com"

gpg_keyid=$(gpg --list-keys | sed -n 4p)
git config --global user.signingkey ${gpg_keyid}

gpg_loc=$(which gpg)
git config --global gpg.program ${gpg_loc}

# Ensure the .git-templates/hooks are executable
git config --global init.templatedir '~/.git_templates'
git config --global commit.template '~/.gitmessage'  

git config --global commit.gpgsign true
git config --global diff.tool vimdiff
# NOTE(Ryan): This reorders the default vimdiff windows, i.e. the staged file is on the left. $
git config --global difftool.vimdiff.cmd 'vim -f -d -c "wincmd h" -c '\''cd "$GIT_PREFIX"'\'' "$REMOTE" "$LOCAL"'
# NOTE(Ryan): This allows the use of :cquit to exit the entire diff process. $
git config --global difftool.trustExitCode true
git config --global difftool.prompt false
git config --global push.default simple
git config --global pull.rebase true
git config --global alias.adog "log --all --decorate --oneline --graph" 
git config --global merge.tool vimdiff
git config --global merge.conflictstyle diff3
git config --global mergetool.prompt false

fi

# TODO(Ryan): Put into scripts folder
git clone --depth 1 https://github.com/torvalds/linux ~/prog/sources/linux
pushd ~/prog/sources/linux
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
popd

git clone --depth 1 https://github.com/gcc-mirror/gcc ~/prog/sources/gcc
pushd ~/prog/sources/gcc
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
popd

git clone --depth 1 https://github.com/freedesktop/xorg-libX11 ~/prog/sources/xorg-libX11
pushd ~/prog/sources/xorg-libX11
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
popd

git clone --depth 1 https://github.com/freedesktop/xorg-libXrender ~/prog/sources/xorg-libXrender 
pushd ~/prog/sources/xorg-libXrender
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
popd

git clone --depth 1 https://github.com/freedesktop/xorg-libXrandr ~/prog/sources/xorg-libXrandr 
pushd ~/prog/sources/xorg-libXrandr
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
popd
